QT += core network serialport widgets

TARGET = V2XPlatform
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += main.cpp\
    v2xplatform.cpp \
    Device/dsrcudpdevice.cpp \
    Fusion/positioning.cpp \
    Device/gpsnetworkdevice.cpp \
    Recording/recorder.cpp \
    Messaging/J2735/Acceleration.c \
    Messaging/J2735/AccelerationConfidence.c \
    Messaging/J2735/AccelerationSet4Way.c \
    Messaging/J2735/AccelSteerYawRateConfidence.c \
    Messaging/J2735/AlaCarte.c \
    Messaging/J2735/AllInclusive.c \
    Messaging/J2735/AmbientAirPressure.c \
    Messaging/J2735/AmbientAirTemperature.c \
    Messaging/J2735/AntennaOffsetSet.c \
    Messaging/J2735/AntiLockBrakeStatus.c \
    Messaging/J2735/Approach.c \
    Messaging/J2735/ApproachNumber.c \
    Messaging/J2735/ApproachObject.c \
    Messaging/J2735/asn_codecs_prim.c \
    Messaging/J2735/asn_SEQUENCE_OF.c \
    Messaging/J2735/asn_SET_OF.c \
    Messaging/J2735/AuxiliaryBrakeStatus.c \
    Messaging/J2735/AxleLocation.c \
    Messaging/J2735/AxleWeight.c \
    Messaging/J2735/BarrierAttributes.c \
    Messaging/J2735/BarrierLane.c \
    Messaging/J2735/BasicSafetyMessage.c \
    Messaging/J2735/BasicSafetyMessageVerbose.c \
    Messaging/J2735/ber_decoder.c \
    Messaging/J2735/ber_tlv_length.c \
    Messaging/J2735/ber_tlv_tag.c \
    Messaging/J2735/BIT_STRING.c \
    Messaging/J2735/BOOLEAN.c \
    Messaging/J2735/BrakeAppliedPressure.c \
    Messaging/J2735/BrakeAppliedStatus.c \
    Messaging/J2735/BrakeBoostApplied.c \
    Messaging/J2735/BrakeSystemStatus.c \
    Messaging/J2735/BSMblob.c \
    Messaging/J2735/BumperHeightFront.c \
    Messaging/J2735/BumperHeightRear.c \
    Messaging/J2735/BumperHeights.c \
    Messaging/J2735/CargoWeight.c \
    Messaging/J2735/Circle.c \
    Messaging/J2735/CodeWord.c \
    Messaging/J2735/CoefficientOfFriction.c \
    Messaging/J2735/ColorState.c \
    Messaging/J2735/CommonSafetyRequest.c \
    Messaging/J2735/ConfidenceSet.c \
    Messaging/J2735/ConnectsTo.c \
    Messaging/J2735/constr_CHOICE.c \
    Messaging/J2735/constr_SEQUENCE_OF.c \
    Messaging/J2735/constr_SEQUENCE.c \
    Messaging/J2735/constr_SET_OF.c \
    Messaging/J2735/constr_TYPE.c \
    Messaging/J2735/constraints.c \
    Messaging/J2735/Count.c \
    Messaging/J2735/CrosswalkLane.c \
    Messaging/J2735/CrosswalkLaneAttributes.c \
    Messaging/J2735/DataParameters.c \
    Messaging/J2735/DDate.c \
    Messaging/J2735/DDateTime.c \
    Messaging/J2735/DDay.c \
    Messaging/J2735/der_encoder.c \
    Messaging/J2735/DescriptiveName.c \
    Messaging/J2735/DFullTime.c \
    Messaging/J2735/DHour.c \
    Messaging/J2735/DirectionOfUse.c \
    Messaging/J2735/DMinute.c \
    Messaging/J2735/DMonth.c \
    Messaging/J2735/DMonthDay.c \
    Messaging/J2735/DOffset.c \
    Messaging/J2735/DriveAxleLiftAirPressure.c \
    Messaging/J2735/DriveAxleLocation.c \
    Messaging/J2735/DriveAxleLubePressure.c \
    Messaging/J2735/DriveAxleTemperature.c \
    Messaging/J2735/DrivenLineOffset.c \
    Messaging/J2735/DrivingWheelAngle.c \
    Messaging/J2735/DSecond.c \
    Messaging/J2735/DSignalSeconds.c \
    Messaging/J2735/DSRCmsgID.c \
    Messaging/J2735/DTime.c \
    Messaging/J2735/DYear.c \
    Messaging/J2735/DYearMonth.c \
    Messaging/J2735/Elevation.c \
    Messaging/J2735/ElevationConfidence.c \
    Messaging/J2735/EmergencyDetails.c \
    Messaging/J2735/EmergencyVehicleAlert.c \
    Messaging/J2735/EssMobileFriction.c \
    Messaging/J2735/EssPrecipRate.c \
    Messaging/J2735/EssPrecipSituation.c \
    Messaging/J2735/EssPrecipYesNo.c \
    Messaging/J2735/EssSolarRadiation.c \
    Messaging/J2735/EventFlags.c \
    Messaging/J2735/ExitService.c \
    Messaging/J2735/Extent.c \
    Messaging/J2735/ExteriorLights.c \
    Messaging/J2735/FullPositionVector.c \
    Messaging/J2735/FurtherInfoID.c \
    Messaging/J2735/GenericSignage.c \
    Messaging/J2735/GPSstatus.c \
    Messaging/J2735/Heading.c \
    Messaging/J2735/HeadingConfidence.c \
    Messaging/J2735/HeadingSlice.c \
    Messaging/J2735/IA5String.c \
    Messaging/J2735/IncidentResponseEquipment.c \
    Messaging/J2735/INTEGER.c \
    Messaging/J2735/Intersection.c \
    Messaging/J2735/IntersectionCollision.c \
    Messaging/J2735/IntersectionID.c \
    Messaging/J2735/IntersectionState.c \
    Messaging/J2735/IntersectionStatusObject.c \
    Messaging/J2735/ITIScodes.c \
    Messaging/J2735/ITIScodesAndText.c \
    Messaging/J2735/ITIStext.c \
    Messaging/J2735/J1939data.c \
    Messaging/J2735/LaneCount.c \
    Messaging/J2735/LaneManeuverCode.c \
    Messaging/J2735/LaneNumber.c \
    Messaging/J2735/LaneSet.c \
    Messaging/J2735/LaneWidth.c \
    Messaging/J2735/Latitude.c \
    Messaging/J2735/LayerID.c \
    Messaging/J2735/LayerType.c \
    Messaging/J2735/LightbarInUse.c \
    Messaging/J2735/Location-quality.c \
    Messaging/J2735/Location-tech.c \
    Messaging/J2735/Longitude.c \
    Messaging/J2735/MapData.c \
    Messaging/J2735/MinuteOfTheYear.c \
    Messaging/J2735/MinutesDuration.c \
    Messaging/J2735/MovementState.c \
    Messaging/J2735/MsgCount.c \
    Messaging/J2735/MsgCRC.c \
    Messaging/J2735/MultiVehicleResponse.c \
    Messaging/J2735/MUTCDCode.c \
    Messaging/J2735/NativeEnumerated.c \
    Messaging/J2735/NativeInteger.c \
    Messaging/J2735/NMEA-Corrections.c \
    Messaging/J2735/NMEA-MsgType.c \
    Messaging/J2735/NMEA-Payload.c \
    Messaging/J2735/NMEA-Revision.c \
    Messaging/J2735/NodeList.c \
    Messaging/J2735/NTCIPVehicleclass.c \
    Messaging/J2735/ObjectCount.c \
    Messaging/J2735/ObstacleDirection.c \
    Messaging/J2735/ObstacleDistance.c \
    Messaging/J2735/OCTET_STRING.c \
    Messaging/J2735/Offsets.c \
    Messaging/J2735/PathHistory.c \
    Messaging/J2735/PathHistoryPointType-01.c \
    Messaging/J2735/PathHistoryPointType-02.c \
    Messaging/J2735/PathHistoryPointType-03.c \
    Messaging/J2735/PathHistoryPointType-04.c \
    Messaging/J2735/PathHistoryPointType-05.c \
    Messaging/J2735/PathHistoryPointType-06.c \
    Messaging/J2735/PathHistoryPointType-07.c \
    Messaging/J2735/PathHistoryPointType-08.c \
    Messaging/J2735/PathHistoryPointType-09.c \
    Messaging/J2735/PathHistoryPointType-10.c \
    Messaging/J2735/PathPrediction.c \
    Messaging/J2735/Payload.c \
    Messaging/J2735/PayloadData.c \
    Messaging/J2735/PedestrianDetect.c \
    Messaging/J2735/PedestrianSignalState.c \
    Messaging/J2735/per_decoder.c \
    Messaging/J2735/per_encoder.c \
    Messaging/J2735/per_opentype.c \
    Messaging/J2735/per_support.c \
    Messaging/J2735/Position3D.c \
    Messaging/J2735/PositionalAccuracy.c \
    Messaging/J2735/PositionConfidence.c \
    Messaging/J2735/PositionConfidenceSet.c \
    Messaging/J2735/PreemptState.c \
    Messaging/J2735/Priority.c \
    Messaging/J2735/PriorityState.c \
    Messaging/J2735/ProbeDataManagement.c \
    Messaging/J2735/ProbeSegmentNumber.c \
    Messaging/J2735/ProbeVehicleData.c \
    Messaging/J2735/RainSensor.c \
    Messaging/J2735/RegionList.c \
    Messaging/J2735/RegionOffsets.c \
    Messaging/J2735/RegionPointSet.c \
    Messaging/J2735/RequestedItem.c \
    Messaging/J2735/ResponderGroupAffected.c \
    Messaging/J2735/ResponseType.c \
    Messaging/J2735/RoadSideAlert.c \
    Messaging/J2735/RoadSignID.c \
    Messaging/J2735/RTCM-Corrections.c \
    Messaging/J2735/RTCM-ID.c \
    Messaging/J2735/RTCM-Payload.c \
    Messaging/J2735/RTCM-Revision.c \
    Messaging/J2735/RTCMHeader.c \
    Messaging/J2735/RTCMmsg.c \
    Messaging/J2735/RTCMPackage.c \
    Messaging/J2735/Sample.c \
    Messaging/J2735/ShapePointSet.c \
    Messaging/J2735/SignalControlZone.c \
    Messaging/J2735/SignalLightState.c \
    Messaging/J2735/SignalReqScheme.c \
    Messaging/J2735/SignalRequest.c \
    Messaging/J2735/SignalRequestMsg.c \
    Messaging/J2735/SignalState.c \
    Messaging/J2735/SignalStatusMessage.c \
    Messaging/J2735/SignPrority.c \
    Messaging/J2735/SirenInUse.c \
    Messaging/J2735/Snapshot.c \
    Messaging/J2735/SnapshotDistance.c \
    Messaging/J2735/SnapshotTime.c \
    Messaging/J2735/SPAT.c \
    Messaging/J2735/SpecialLane.c \
    Messaging/J2735/SpecialLaneAttributes.c \
    Messaging/J2735/SpecialSignalState.c \
    Messaging/J2735/Speed.c \
    Messaging/J2735/SpeedandHeadingandThrottleConfidence.c \
    Messaging/J2735/SpeedConfidence.c \
    Messaging/J2735/SpeedLimit.c \
    Messaging/J2735/StabilityControlStatus.c \
    Messaging/J2735/StateConfidence.c \
    Messaging/J2735/SteeringAxleLubePressure.c \
    Messaging/J2735/SteeringAxleTemperature.c \
    Messaging/J2735/SteeringWheelAngle.c \
    Messaging/J2735/SteeringWheelAngleConfidence.c \
    Messaging/J2735/SteeringWheelAngleRateOfChange.c \
    Messaging/J2735/SunSensor.c \
    Messaging/J2735/TemporaryID.c \
    Messaging/J2735/TermDistance.c \
    Messaging/J2735/TermTime.c \
    Messaging/J2735/TestDataFrameV2VI.c \
    Messaging/J2735/ThrottleConfidence.c \
    Messaging/J2735/ThrottlePosition.c \
    Messaging/J2735/TimeConfidence.c \
    Messaging/J2735/TimeMark.c \
    Messaging/J2735/TireLeakageRate.c \
    Messaging/J2735/TireLocation.c \
    Messaging/J2735/TirePressure.c \
    Messaging/J2735/TirePressureThresholdDetection.c \
    Messaging/J2735/TireTemp.c \
    Messaging/J2735/TractionControlState.c \
    Messaging/J2735/TrailerWeight.c \
    Messaging/J2735/TransitPreEmptionRequest.c \
    Messaging/J2735/TransitStatus.c \
    Messaging/J2735/TransmissionAndSpeed.c \
    Messaging/J2735/TransmissionState.c \
    Messaging/J2735/TravelerInformation.c \
    Messaging/J2735/TravelerInfoType.c \
    Messaging/J2735/TxTime.c \
    Messaging/J2735/UniqueMSGID.c \
    Messaging/J2735/URL-Base.c \
    Messaging/J2735/URL-Link.c \
    Messaging/J2735/URL-Short.c \
    Messaging/J2735/ValidRegion.c \
    Messaging/J2735/VehicleComputedLane.c \
    Messaging/J2735/VehicleDataV2VI.c \
    Messaging/J2735/VehicleGroupAffected.c \
    Messaging/J2735/VehicleHeight.c \
    Messaging/J2735/VehicleIdent.c \
    Messaging/J2735/VehicleLaneAttributes.c \
    Messaging/J2735/VehicleLength.c \
    Messaging/J2735/VehicleMass.c \
    Messaging/J2735/VehicleReferenceLane.c \
    Messaging/J2735/VehicleRequestStatus.c \
    Messaging/J2735/VehicleSafetyExtension.c \
    Messaging/J2735/VehicleSize.c \
    Messaging/J2735/VehicleStatus.c \
    Messaging/J2735/VehicleStatusDeviceTypeTag.c \
    Messaging/J2735/VehicleStatusRequest.c \
    Messaging/J2735/VehicleType.c \
    Messaging/J2735/VehicleWidth.c \
    Messaging/J2735/VerticalAcceleration.c \
    Messaging/J2735/VerticalAccelerationThreshold.c \
    Messaging/J2735/VINstring.c \
    Messaging/J2735/WheelEndElectFault.c \
    Messaging/J2735/WheelSensorStatus.c \
    Messaging/J2735/WiperRate.c \
    Messaging/J2735/WiperStatus.c \
    Messaging/J2735/WiperStatusFront.c \
    Messaging/J2735/WiperStatusRear.c \
    Messaging/J2735/WorkZone.c \
    Messaging/J2735/xer_decoder.c \
    Messaging/J2735/xer_encoder.c \
    Messaging/J2735/xer_support.c \
    Messaging/J2735/YawRate.c \
    Messaging/J2735/YawRateConfidence.c \
    Messaging/bsmmessage.cpp \
    WorldModel/world.cpp \
    WorldModel/vehicle.cpp \
    Application/ActiveSafety/carData.cpp \
    Application/ActiveSafety/crashpair.cpp \
    Application/ActiveSafety/activesafety.cpp \
    Device/gpsserialportdevice.cpp \
    Device/canserialportdevice.cpp \
    Device/abstractdevice.cpp \
    Messaging/spatmessage.cpp \
    Device/serialportframedeviceex.cpp \
    Recording/player.cpp \
    Sensor/sensor.cpp \
    Messaging/mapmessage.cpp \
    Application/SpeedGuidance/judge.cpp \
    Application/SpeedGuidance/SpeedGuidance.cpp \
    Messaging/J2735/bsmreceive.cpp \
    Messaging/J2735/bsmsend.cpp \
    Application/ActiveSafety/computetools.cpp \
    Application/LightChoose/lightchoose.cpp \
    Push/pushhmi.cpp \
    Application/ActiveSafety/collisionpriority.cpp \
    UI/datatable.cpp \
    UI/mainwindow.cpp \
    UI/paintwidget.cpp \
    UI/sdatawidget.cpp \
    UI/speedguide.cpp

HEADERS  += Utils/coordinatetransform.h \
    v2xplatform.h \
    Sensor/gps.h \
    Sensor/can.h \
    Device/dsrcudpdevice.h \
    Fusion/positioning.h \
    Sensor/dsrc.h \
    Device/gpsnetworkdevice.h \
    Device/gpsnetworkhelper.h \
    Recording/recorder.h \
    Messaging/J2735/Acceleration.h \
    Messaging/J2735/AccelerationConfidence.h \
    Messaging/J2735/AccelerationSet4Way.h \
    Messaging/J2735/AccelSteerYawRateConfidence.h \
    Messaging/J2735/AlaCarte.h \
    Messaging/J2735/AllInclusive.h \
    Messaging/J2735/AmbientAirPressure.h \
    Messaging/J2735/AmbientAirTemperature.h \
    Messaging/J2735/AntennaOffsetSet.h \
    Messaging/J2735/AntiLockBrakeStatus.h \
    Messaging/J2735/Approach.h \
    Messaging/J2735/ApproachNumber.h \
    Messaging/J2735/ApproachObject.h \
    Messaging/J2735/asn_application.h \
    Messaging/J2735/asn_codecs_prim.h \
    Messaging/J2735/asn_codecs.h \
    Messaging/J2735/asn_internal.h \
    Messaging/J2735/asn_SEQUENCE_OF.h \
    Messaging/J2735/asn_SET_OF.h \
    Messaging/J2735/asn_system.h \
    Messaging/J2735/AuxiliaryBrakeStatus.h \
    Messaging/J2735/AxleLocation.h \
    Messaging/J2735/AxleWeight.h \
    Messaging/J2735/BarrierAttributes.h \
    Messaging/J2735/BarrierLane.h \
    Messaging/J2735/BasicSafetyMessage.h \
    Messaging/J2735/BasicSafetyMessageVerbose.h \
    Messaging/J2735/ber_decoder.h \
    Messaging/J2735/ber_tlv_length.h \
    Messaging/J2735/ber_tlv_tag.h \
    Messaging/J2735/BIT_STRING.h \
    Messaging/J2735/BOOLEAN.h \
    Messaging/J2735/BrakeAppliedPressure.h \
    Messaging/J2735/BrakeAppliedStatus.h \
    Messaging/J2735/BrakeBoostApplied.h \
    Messaging/J2735/BrakeSystemStatus.h \
    Messaging/J2735/BSMblob.h \
    Messaging/J2735/BumperHeightFront.h \
    Messaging/J2735/BumperHeightRear.h \
    Messaging/J2735/BumperHeights.h \
    Messaging/J2735/CargoWeight.h \
    Messaging/J2735/Circle.h \
    Messaging/J2735/CodeWord.h \
    Messaging/J2735/CoefficientOfFriction.h \
    Messaging/J2735/ColorState.h \
    Messaging/J2735/CommonSafetyRequest.h \
    Messaging/J2735/ConfidenceSet.h \
    Messaging/J2735/config.h \
    Messaging/J2735/ConnectsTo.h \
    Messaging/J2735/constr_CHOICE.h \
    Messaging/J2735/constr_SEQUENCE_OF.h \
    Messaging/J2735/constr_SEQUENCE.h \
    Messaging/J2735/constr_SET_OF.h \
    Messaging/J2735/constr_TYPE.h \
    Messaging/J2735/constraints.h \
    Messaging/J2735/Count.h \
    Messaging/J2735/CrosswalkLane.h \
    Messaging/J2735/CrosswalkLaneAttributes.h \
    Messaging/J2735/DataParameters.h \
    Messaging/J2735/DDate.h \
    Messaging/J2735/DDateTime.h \
    Messaging/J2735/DDay.h \
    Messaging/J2735/debug-levels.h \
    Messaging/J2735/der_encoder.h \
    Messaging/J2735/DescriptiveName.h \
    Messaging/J2735/DFullTime.h \
    Messaging/J2735/DHour.h \
    Messaging/J2735/DirectionOfUse.h \
    Messaging/J2735/DMinute.h \
    Messaging/J2735/DMonth.h \
    Messaging/J2735/DMonthDay.h \
    Messaging/J2735/DOffset.h \
    Messaging/J2735/DriveAxleLiftAirPressure.h \
    Messaging/J2735/DriveAxleLocation.h \
    Messaging/J2735/DriveAxleLubePressure.h \
    Messaging/J2735/DriveAxleTemperature.h \
    Messaging/J2735/DrivenLineOffset.h \
    Messaging/J2735/DrivingWheelAngle.h \
    Messaging/J2735/DSecond.h \
    Messaging/J2735/DSignalSeconds.h \
    Messaging/J2735/DSRCmsgID.h \
    Messaging/J2735/DTime.h \
    Messaging/J2735/DYear.h \
    Messaging/J2735/DYearMonth.h \
    Messaging/J2735/Elevation.h \
    Messaging/J2735/ElevationConfidence.h \
    Messaging/J2735/EmergencyDetails.h \
    Messaging/J2735/EmergencyVehicleAlert.h \
    Messaging/J2735/EssMobileFriction.h \
    Messaging/J2735/EssPrecipRate.h \
    Messaging/J2735/EssPrecipSituation.h \
    Messaging/J2735/EssPrecipYesNo.h \
    Messaging/J2735/EssSolarRadiation.h \
    Messaging/J2735/EventFlags.h \
    Messaging/J2735/ExitService.h \
    Messaging/J2735/Extent.h \
    Messaging/J2735/ExteriorLights.h \
    Messaging/J2735/FullPositionVector.h \
    Messaging/J2735/FurtherInfoID.h \
    Messaging/J2735/GenericSignage.h \
    Messaging/J2735/GPSstatus.h \
    Messaging/J2735/Heading.h \
    Messaging/J2735/HeadingConfidence.h \
    Messaging/J2735/HeadingSlice.h \
    Messaging/J2735/IA5String.h \
    Messaging/J2735/IncidentResponseEquipment.h \
    Messaging/J2735/INTEGER.h \
    Messaging/J2735/Intersection.h \
    Messaging/J2735/IntersectionCollision.h \
    Messaging/J2735/IntersectionID.h \
    Messaging/J2735/IntersectionState.h \
    Messaging/J2735/IntersectionStatusObject.h \
    Messaging/J2735/ITIScodes.h \
    Messaging/J2735/ITIScodesAndText.h \
    Messaging/J2735/ITIStext.h \
    Messaging/J2735/J1939data.h \
    Messaging/J2735/LaneCount.h \
    Messaging/J2735/LaneManeuverCode.h \
    Messaging/J2735/LaneNumber.h \
    Messaging/J2735/LaneSet.h \
    Messaging/J2735/LaneWidth.h \
    Messaging/J2735/Latitude.h \
    Messaging/J2735/LayerID.h \
    Messaging/J2735/LayerType.h \
    Messaging/J2735/LightbarInUse.h \
    Messaging/J2735/Location-quality.h \
    Messaging/J2735/Location-tech.h \
    Messaging/J2735/Longitude.h \
    Messaging/J2735/MapData.h \
    Messaging/J2735/MinuteOfTheYear.h \
    Messaging/J2735/MinutesDuration.h \
    Messaging/J2735/MovementState.h \
    Messaging/J2735/MsgCount.h \
    Messaging/J2735/MsgCRC.h \
    Messaging/J2735/MultiVehicleResponse.h \
    Messaging/J2735/MUTCDCode.h \
    Messaging/J2735/NativeEnumerated.h \
    Messaging/J2735/NativeInteger.h \
    Messaging/J2735/NMEA-Corrections.h \
    Messaging/J2735/NMEA-MsgType.h \
    Messaging/J2735/NMEA-Payload.h \
    Messaging/J2735/NMEA-Revision.h \
    Messaging/J2735/NodeList.h \
    Messaging/J2735/NTCIPVehicleclass.h \
    Messaging/J2735/ObjectCount.h \
    Messaging/J2735/ObstacleDirection.h \
    Messaging/J2735/ObstacleDistance.h \
    Messaging/J2735/OCTET_STRING.h \
    Messaging/J2735/Offsets.h \
    Messaging/J2735/PathHistory.h \
    Messaging/J2735/PathHistoryPointType-01.h \
    Messaging/J2735/PathHistoryPointType-02.h \
    Messaging/J2735/PathHistoryPointType-03.h \
    Messaging/J2735/PathHistoryPointType-04.h \
    Messaging/J2735/PathHistoryPointType-05.h \
    Messaging/J2735/PathHistoryPointType-06.h \
    Messaging/J2735/PathHistoryPointType-07.h \
    Messaging/J2735/PathHistoryPointType-08.h \
    Messaging/J2735/PathHistoryPointType-09.h \
    Messaging/J2735/PathHistoryPointType-10.h \
    Messaging/J2735/PathPrediction.h \
    Messaging/J2735/Payload.h \
    Messaging/J2735/PayloadData.h \
    Messaging/J2735/PedestrianDetect.h \
    Messaging/J2735/PedestrianSignalState.h \
    Messaging/J2735/per_decoder.h \
    Messaging/J2735/per_encoder.h \
    Messaging/J2735/per_opentype.h \
    Messaging/J2735/per_support.h \
    Messaging/J2735/Position3D.h \
    Messaging/J2735/PositionalAccuracy.h \
    Messaging/J2735/PositionConfidence.h \
    Messaging/J2735/PositionConfidenceSet.h \
    Messaging/J2735/PreemptState.h \
    Messaging/J2735/Priority.h \
    Messaging/J2735/PriorityState.h \
    Messaging/J2735/ProbeDataManagement.h \
    Messaging/J2735/ProbeSegmentNumber.h \
    Messaging/J2735/ProbeVehicleData.h \
    Messaging/J2735/RainSensor.h \
    Messaging/J2735/RegionList.h \
    Messaging/J2735/RegionOffsets.h \
    Messaging/J2735/RegionPointSet.h \
    Messaging/J2735/RequestedItem.h \
    Messaging/J2735/ResponderGroupAffected.h \
    Messaging/J2735/ResponseType.h \
    Messaging/J2735/RoadSideAlert.h \
    Messaging/J2735/RoadSignID.h \
    Messaging/J2735/RTCM-Corrections.h \
    Messaging/J2735/RTCM-ID.h \
    Messaging/J2735/RTCM-Payload.h \
    Messaging/J2735/RTCM-Revision.h \
    Messaging/J2735/RTCMHeader.h \
    Messaging/J2735/RTCMmsg.h \
    Messaging/J2735/RTCMPackage.h \
    Messaging/J2735/Sample.h \
    Messaging/J2735/ShapePointSet.h \
    Messaging/J2735/SignalControlZone.h \
    Messaging/J2735/SignalLightState.h \
    Messaging/J2735/SignalReqScheme.h \
    Messaging/J2735/SignalRequest.h \
    Messaging/J2735/SignalRequestMsg.h \
    Messaging/J2735/SignalState.h \
    Messaging/J2735/SignalStatusMessage.h \
    Messaging/J2735/SignPrority.h \
    Messaging/J2735/SirenInUse.h \
    Messaging/J2735/Snapshot.h \
    Messaging/J2735/SnapshotDistance.h \
    Messaging/J2735/SnapshotTime.h \
    Messaging/J2735/SPAT.h \
    Messaging/J2735/SpecialLane.h \
    Messaging/J2735/SpecialLaneAttributes.h \
    Messaging/J2735/SpecialSignalState.h \
    Messaging/J2735/Speed.h \
    Messaging/J2735/SpeedandHeadingandThrottleConfidence.h \
    Messaging/J2735/SpeedConfidence.h \
    Messaging/J2735/SpeedLimit.h \
    Messaging/J2735/StabilityControlStatus.h \
    Messaging/J2735/StateConfidence.h \
    Messaging/J2735/SteeringAxleLubePressure.h \
    Messaging/J2735/SteeringAxleTemperature.h \
    Messaging/J2735/SteeringWheelAngle.h \
    Messaging/J2735/SteeringWheelAngleConfidence.h \
    Messaging/J2735/SteeringWheelAngleRateOfChange.h \
    Messaging/J2735/SunSensor.h \
    Messaging/J2735/TemporaryID.h \
    Messaging/J2735/TermDistance.h \
    Messaging/J2735/TermTime.h \
    Messaging/J2735/TestDataFrameV2VI.h \
    Messaging/J2735/ThrottleConfidence.h \
    Messaging/J2735/ThrottlePosition.h \
    Messaging/J2735/TimeConfidence.h \
    Messaging/J2735/TimeMark.h \
    Messaging/J2735/TireLeakageRate.h \
    Messaging/J2735/TireLocation.h \
    Messaging/J2735/TirePressure.h \
    Messaging/J2735/TirePressureThresholdDetection.h \
    Messaging/J2735/TireTemp.h \
    Messaging/J2735/TractionControlState.h \
    Messaging/J2735/TrailerWeight.h \
    Messaging/J2735/TransitPreEmptionRequest.h \
    Messaging/J2735/TransitStatus.h \
    Messaging/J2735/TransmissionAndSpeed.h \
    Messaging/J2735/TransmissionState.h \
    Messaging/J2735/TravelerInformation.h \
    Messaging/J2735/TravelerInfoType.h \
    Messaging/J2735/TxTime.h \
    Messaging/J2735/UniqueMSGID.h \
    Messaging/J2735/URL-Base.h \
    Messaging/J2735/URL-Link.h \
    Messaging/J2735/URL-Short.h \
    Messaging/J2735/ValidRegion.h \
    Messaging/J2735/VehicleComputedLane.h \
    Messaging/J2735/VehicleDataV2VI.h \
    Messaging/J2735/VehicleGroupAffected.h \
    Messaging/J2735/VehicleHeight.h \
    Messaging/J2735/VehicleIdent.h \
    Messaging/J2735/VehicleLaneAttributes.h \
    Messaging/J2735/VehicleLength.h \
    Messaging/J2735/VehicleMass.h \
    Messaging/J2735/VehicleReferenceLane.h \
    Messaging/J2735/VehicleRequestStatus.h \
    Messaging/J2735/VehicleSafetyExtension.h \
    Messaging/J2735/VehicleSize.h \
    Messaging/J2735/VehicleStatus.h \
    Messaging/J2735/VehicleStatusDeviceTypeTag.h \
    Messaging/J2735/VehicleStatusRequest.h \
    Messaging/J2735/VehicleType.h \
    Messaging/J2735/VehicleWidth.h \
    Messaging/J2735/VerticalAcceleration.h \
    Messaging/J2735/VerticalAccelerationThreshold.h \
    Messaging/J2735/VINstring.h \
    Messaging/J2735/WheelEndElectFault.h \
    Messaging/J2735/WheelSensorStatus.h \
    Messaging/J2735/WiperRate.h \
    Messaging/J2735/WiperStatus.h \
    Messaging/J2735/WiperStatusFront.h \
    Messaging/J2735/WiperStatusRear.h \
    Messaging/J2735/WorkZone.h \
    Messaging/J2735/xer_decoder.h \
    Messaging/J2735/xer_encoder.h \
    Messaging/J2735/xer_support.h \
    Messaging/J2735/YawRate.h \
    Messaging/J2735/YawRateConfidence.h \
    Messaging/bsmmessage.h \
    WorldModel/world.h \
    Application/ActiveSafety/carData.h \
    Application/ActiveSafety/crashpair.h \
    Application/ActiveSafety/activesafety.h \
    Device/canserialportdevice.h \
    Device/gpsserialportdevice.h \
    Device/abstractdevice.h \
    Messaging/spatmessage.h \
    Device/serialportframedeviceex.h \
    Recording/player.h \
    Sensor/abstractsensor.h \
    Messaging/mapmessage.h \
    WorldModel/worldobject.h \
    Application/SpeedGuidance/judge.h \
    Application/SpeedGuidance/SpeedGuidance.h \
    Messaging/J2735/bsmreceive.h \
    Messaging/J2735/bsmsend.h \
    Recording/singlesensorplayer.hpp \
    Application/ActiveSafety/computetools.h \
    Push/pushhmi.h \
    Application/ActiveSafety/collisionpriority.h \
    UI/datatable.h \
    UI/mainwindow.h \
    UI/paintwidget.h \
    UI/sdatawidget.h \
    UI/speedguide.h

INCLUDEPATH += "../ThirdParty/tclap/include" \
                Messaging/J2735

CONFIG += c++11

LIBS += -L../../Source/ThirdParty/GPSd -lgps_static
